spring.application.name=app

## DB connection
spring.datasource.url=jdbc:mysql://localhost:3306/staffy
spring.datasource.username=root
spring.datasource.password=Harsh@19

## JPA / Hibernate

#creates tables automatically
#updates schema if entity changes
spring.jpa.hibernate.ddl-auto=update

#Prints SQL queries in console
#helps debugging
spring.jpa.show-sql=true

#Dialect tells Hibernate, Im using MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Server
server.port=8080

#JWT token secret key (mySuperSecretKeyForJwtAuthenticationThatIsAtLeast32BytesLong)
jwt.secret=bXlTdXBlclNlY3JldEtleUZvckp3dEF1dGhlbnRpY2F0aW9uVGhhdElzQXRMZWFzdDMyQnl0ZXNMb25n